[theme]
primaryColor = "#4CAF50"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#e0e0e0"
textColor = "#212121"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
installTracker = false

[deprecation]
showPyplotGlobalUse = false
