# Credenciales para Google Sheets
[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/xxx/edit"

# Configuración para autenticación simple con contraseña
password = "cvprocessor2025"

# Clave de API de OpenAI
openai_api_key = "sk-xxxx-xxxx-xxxx-xxxx-xxxx"

# Configuración para OAuth (opcional, para autenticación con Google)
[oauth]
client_id = "xxx.apps.googleusercontent.com"
client_secret = "xxx"

# Configuración de cookies
[cookie]
expiry_days = 30
key = "cvprocessor_signature_key_2025"
name = "cvprocessor_cookie"
